import { Course } from '@/types';

export const courses: Course[] = [
  {
    id: '1',
    slug: 'ingles-completo',
    title: 'Inglês Completo - Do Zero à Fluência',
    description: 'Aprenda inglês do zero ao avançado com metodologia comprovada. Curso completo com certificado reconhecido, aulas práticas e suporte individualizado.',
    shortDescription: 'Domine o inglês com método eficaz e certificado reconhecido',
    price: 39.90,
    originalPrice: 197.00,
    category: 'Idiomas',
    level: 'Iniciante',
    duration: '120 horas',
    students: 15847,
    rating: 4.9,
    features: [
      'Acesso vitalício',
      'Certificado reconhecido',
      'Aulas ao vivo semanais',
      'Material didático incluso',
      'Exercícios práticos',
      'Suporte do professor',
      'Comunidade exclusiva',
      'App mobile',
    ],
    modules: [
      {
        id: 'm1',
        title: 'Fundamentos do Inglês',
        lessons: 15,
        duration: '12 horas',
      },
      {
        id: 'm2',
        title: 'Gramática Essencial',
        lessons: 20,
        duration: '18 horas',
      },
      {
        id: 'm3',
        title: 'Conversação Básica',
        lessons: 18,
        duration: '15 horas',
      },
      {
        id: 'm4',
        title: 'Inglês Intermediário',
        lessons: 25,
        duration: '22 horas',
      },
      {
        id: 'm5',
        title: 'Business English',
        lessons: 20,
        duration: '20 horas',
      },
      {
        id: 'm6',
        title: 'Fluência Avançada',
        lessons: 22,
        duration: '25 horas',
      },
    ],
    instructor: {
      name: 'Prof. Amanda Silva',
      bio: 'Formada em Letras pela USP, com certificação internacional TEFL e 12 anos de experiência em ensino de idiomas.',
      avatar: '👩‍🏫',
    },
  },
  {
    id: '2',
    slug: 'espanhol-pratico',
    title: 'Espanhol Prático para Viagens',
    description: 'Aprenda espanhol de forma rápida e prática, focado em conversação e situações reais do dia a dia.',
    shortDescription: 'Espanhol essencial para suas viagens',
    price: 29.90,
    originalPrice: 147.00,
    category: 'Idiomas',
    level: 'Iniciante',
    duration: '60 horas',
    students: 8934,
    rating: 4.8,
    features: [
      'Acesso vitalício',
      'Certificado digital',
      'Foco em conversação',
      'Simulações práticas',
      'Guia de pronúncia',
      'Exercícios interativos',
    ],
    modules: [
      {
        id: 'm1',
        title: 'Saudações e Apresentações',
        lessons: 8,
        duration: '6 horas',
      },
      {
        id: 'm2',
        title: 'No Restaurante e Hotel',
        lessons: 10,
        duration: '8 horas',
      },
      {
        id: 'm3',
        title: 'Fazendo Compras',
        lessons: 8,
        duration: '7 horas',
      },
      {
        id: 'm4',
        title: 'Transporte e Direções',
        lessons: 9,
        duration: '8 horas',
      },
    ],
    instructor: {
      name: 'Prof. Carlos Rodriguez',
      bio: 'Professor nativo com mais de 15 anos ensinando espanhol para brasileiros.',
      avatar: '👨‍🏫',
    },
  },
  {
    id: '3',
    slug: 'frances-basico',
    title: 'Francês Básico - Primeiros Passos',
    description: 'Introdução completa ao francês com foco na pronúncia correta e cultura francesa.',
    shortDescription: 'Primeiros passos no idioma do amor',
    price: 34.90,
    originalPrice: 167.00,
    category: 'Idiomas',
    level: 'Iniciante',
    duration: '80 horas',
    students: 6521,
    rating: 4.7,
    features: [
      'Acesso vitalício',
      'Certificado reconhecido',
      'Aulas de pronúncia',
      'Material em PDF',
      'Exercícios práticos',
      'Cultura francesa',
    ],
    modules: [
      {
        id: 'm1',
        title: 'Alfabeto e Pronúncia',
        lessons: 10,
        duration: '8 horas',
      },
      {
        id: 'm2',
        title: 'Gramática Básica',
        lessons: 15,
        duration: '12 horas',
      },
      {
        id: 'm3',
        title: 'Vocabulário Essencial',
        lessons: 12,
        duration: '10 horas',
      },
    ],
    instructor: {
      name: 'Prof. Sophie Martin',
      bio: 'Professora nativa com especialização em ensino de francês como língua estrangeira.',
      avatar: '👩‍🏫',
    },
  },
  {
    id: '4',
    slug: 'alemao-negocios',
    title: 'Alemão para Negócios',
    description: 'Curso especializado em alemão corporativo e comunicação empresarial.',
    shortDescription: 'Alemão focado no mundo dos negócios',
    price: 49.90,
    originalPrice: 247.00,
    category: 'Idiomas',
    level: 'Intermediário',
    duration: '100 horas',
    students: 4156,
    rating: 4.9,
    features: [
      'Acesso vitalício',
      'Certificado internacional',
      'Networking exclusivo',
      'Cases reais',
      'Mentoria individual',
      'Vocabulário técnico',
    ],
    modules: [
      {
        id: 'm1',
        title: 'Comunicação Corporativa',
        lessons: 18,
        duration: '15 horas',
      },
      {
        id: 'm2',
        title: 'Reuniões e Apresentações',
        lessons: 16,
        duration: '14 horas',
      },
      {
        id: 'm3',
        title: 'E-mails Profissionais',
        lessons: 12,
        duration: '10 horas',
      },
    ],
    instructor: {
      name: 'Prof. Hans Müller',
      bio: 'Executivo bilíngue com MBA e 20 anos de experiência no mercado corporativo.',
      avatar: '👨‍💼',
    },
  },
  {
    id: '5',
    slug: 'italiano-conversacao',
    title: 'Italiano - Conversação Avançada',
    description: 'Aprimore sua fluência em italiano com foco total em conversação natural.',
    shortDescription: 'Desenvolva fluência real em italiano',
    price: 44.90,
    originalPrice: 217.00,
    category: 'Idiomas',
    level: 'Avançado',
    duration: '90 horas',
    students: 3892,
    rating: 4.8,
    features: [
      'Acesso vitalício',
      'Aulas ao vivo diárias',
      'Conversação com nativos',
      'Imersão cultural',
      'Certificado C1',
      'Material exclusivo',
    ],
    modules: [
      {
        id: 'm1',
        title: 'Debates e Discussões',
        lessons: 14,
        duration: '12 horas',
      },
      {
        id: 'm2',
        title: 'Expressões Idiomáticas',
        lessons: 12,
        duration: '10 horas',
      },
      {
        id: 'm3',
        title: 'Cultura Italiana',
        lessons: 15,
        duration: '13 horas',
      },
    ],
    instructor: {
      name: 'Prof. Giulia Rossi',
      bio: 'Professora nativa de Roma com doutorado em Linguística Aplicada.',
      avatar: '👩‍🎓',
    },
  },
  {
    id: '6',
    slug: 'japones-iniciante',
    title: 'Japonês para Iniciantes',
    description: 'Introdução completa ao japonês, incluindo hiragana, katakana e kanji básico.',
    shortDescription: 'Descubra o fascinante mundo do japonês',
    price: 39.90,
    originalPrice: 197.00,
    category: 'Idiomas',
    level: 'Iniciante',
    duration: '110 horas',
    students: 7234,
    rating: 4.9,
    features: [
      'Acesso vitalício',
      'Certificado JLPT N5',
      'Escrita japonesa',
      'Cultura e tradições',
      'Kanji interativo',
      'Áudio nativo',
    ],
    modules: [
      {
        id: 'm1',
        title: 'Hiragana e Katakana',
        lessons: 16,
        duration: '14 horas',
      },
      {
        id: 'm2',
        title: 'Gramática Básica',
        lessons: 20,
        duration: '18 horas',
      },
      {
        id: 'm3',
        title: 'Kanji Essencial',
        lessons: 18,
        duration: '16 horas',
      },
    ],
    instructor: {
      name: 'Prof. Yuki Tanaka',
      bio: 'Professora nativa de Tóquio, especialista em ensino de japonês para estrangeiros.',
      avatar: '👩‍🏫',
    },
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find(course => course.slug === slug);
}

export function getCourseById(id: string): Course | undefined {
  return courses.find(course => course.id === id);
}
